services:
    backend:
        build:
            context: ./docker/images/backend/
        networks:
            - dev
        volumes:
            - "./:/var/www/html"
            - "./docker/config/backend/php.ini:/etc/php/8.3/fpm/php.ini"

    webserver:
        image: nginx:latest
        networks:
            - dev
        ports:
            - "8001:80"
        volumes:
            - "./:/var/www/html"
            - "./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"

networks:
    dev:
